#!/usr/bin/env node

import { createHash } from "node:crypto";
import { readdir, readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));
const resourcesRoot = path.join(root, "resources");
const outputPath = path.join(root, "data", "resources.js");
const courseSlugs = ["eai-6401", "eai-6402", "eai-6403"];
const supported = new Set([".pdf", ".ppt", ".pptx"]);

function titleFromFilename(filename) {
  return path.basename(filename, path.extname(filename))
    .replace(/^\d{4}-\d{2}-\d{2}[-_ ]*/, "")
    .replace(/[-_]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function webPath(relativePath) {
  return relativePath.split(path.sep).map(encodeURIComponent).join("/");
}

async function readMetadata(courseDir) {
  try {
    return JSON.parse(await readFile(path.join(courseDir, "_index.json"), "utf8"));
  } catch {
    return {};
  }
}

async function walk(directory, base = directory) {
  const files = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    if (entry.name.startsWith(".") || entry.name === "_index.json" || entry.name === "README.md") continue;
    const fullPath = path.join(directory, entry.name);
    if (entry.isDirectory()) files.push(...await walk(fullPath, base));
    else if (supported.has(path.extname(entry.name).toLowerCase())) files.push(path.relative(base, fullPath));
  }
  return files;
}

const indexed = [];
for (const course of courseSlugs) {
  const courseDir = path.join(resourcesRoot, course);
  const metadata = await readMetadata(courseDir);
  const files = await walk(courseDir);
  for (const filename of files) {
    const extension = path.extname(filename).toLowerCase();
    const details = metadata[filename] ?? metadata[path.basename(filename)] ?? {};
    const relativePath = path.join("resources", course, filename);
    const fileStats = await stat(path.join(courseDir, filename));
    indexed.push({
      id: createHash("sha256").update(`${course}:${filename}`).digest("hex").slice(0, 12),
      course,
      title: details.title || titleFromFilename(filename),
      titleHi: details.titleHi || "",
      description: details.description || "",
      descriptionHi: details.descriptionHi || "",
      language: details.language || "en",
      kind: extension === ".pdf" ? "pdf" : "presentation",
      extension: extension.slice(1),
      date: details.date || "",
      path: webPath(relativePath),
      bytes: fileStats.size
    });
  }
}

indexed.sort((left, right) =>
  left.course.localeCompare(right.course) ||
  (left.date || "9999").localeCompare(right.date || "9999") ||
  left.title.localeCompare(right.title)
);

await writeFile(
  outputPath,
  `// Generated by tools/index_resources.mjs. Do not edit by hand.\nexport const courseResources = ${JSON.stringify(indexed, null, 2)};\n`
);
console.log(`Indexed ${indexed.length} public course resource${indexed.length === 1 ? "" : "s"}.`);
